### ISSUE TITLE
Resources models always use default handler by default

### ISSUE THREAD

**Issue by samitnuk** [Mangopay/mangopay2-python-sdk#158] opened 2018-04-23 15:07 UTC
Hello!

In our project, we have next settings for `handler` (_custom_ handler):
```
handler = APIRequest(sandbox=False,  timeout=300)
```
We found that resources models (e.g. `Document`) ignore _custom_ handler and use default handler instead:
```
>>> handler.timeout
300

>>> Document().handler.timeout
30.0
```

Setting of _custom_ handler will be used only in case we will pass _custom_ handler explicitly to the resource model:
```
>>> Document(handler=handler).handler.timeout
300
```

In docs I cannot find information that we should pass _custom_ handler to each resource we create. Probably this should be fixed or at least indicated in docs.

**Comment by sasha0** [comment] 2018-04-23 15:16
The main problem is that in order to override default `auth_manager`, `timeout` or `proxies` parameters of the `APIRequest` we have to explicitly pass custom handler with overridden parameters every time we initiate resource model, because instead of `api_url`, `client_id` and `passphrase` which stored in the global namespace.

**Comment by mickaelpois** [comment] 2018-08-24 08:58
Thanks for your remarks.
We will enhance our handler very soon, to give you some best ways to use this SDK.
This issue is a duplicate of #134, please feel free to post on it to give us more feedback or complains about it ;)

Mickaël

**Closed by mickaelpois** 2018-08-24 08:58 UTC
