### ISSUE TITLE
Improvement suggestions

### ISSUE THREAD

**Issue by rclement** [Mangopay/mangopay2-python-sdk#195] opened 2019-07-10 12:14 UTC
Hi team Mangopay,

Sorry to bring this to you, but I feel this is necessary upon the latest release (`3.7.0`). This is not purely complaint but a way to give you feedback about what went wrong as a user of this SDK and pointers on how to improve the usage experience:

- Today, perfoming a check for updates with `pipenv` tells us there is a new version of `mangopay-sdk`. Great, let's see! Ok, we're upgrading from `3.5.1` to ... `3.7.0`?! Where did `3.6.0` go?

  * A quick check on this repository, no `CHANGELOG.md`, but changelogs in GitHub Releases, stating there was at some point a version `3.6.0`... 8 month ago!
  * A quick check on [pypi.org](https://pypi.org/project/mangopaysdk/#history): no version `3.6.0` has been published, ever!
  * How is that possible even though there is a Travis CI/CD config for this repo, supposedly uploading new releases to [pypi.org](https://pypi.org/project/mangopaysdk)?
  * Was there a reason not to upload this version?

- Upgrade to version `3.7.0` and run QA pipelines:

  * Tests broke, everywhere where Mangopay is involved, even though we are using fixtures/mocks/etc.
  * Apparently there was a breaking change introduced by the previous version `3.6.0`
  * This change is not explicitely stated as `BREAKING` in the GitHub Release statement!
  * Changing `mangopay.passphrase` to `mangopay.apikey` was a quick fix, but we should not have to check for the Git history and try to pin-point where the culprit is.

- The changelog for version `3.7.0` states: `This new 3.7 version of our Node.js SDK includes 2 essential features related to Compliance needs...`. I know you are busy, but changing "Node.js" to "Python" would have been nice (and avoid mental confusion for those of us who are using lots of various programming languages and SDKs/frameworks everyday).

Some improvement suggestions:

- Fix the Travis CI/CD job for automatic release deployment to PyPI.

- Keep a proper changelog within the Git repository itself as `CHANGELOG.md` (and not just GitHub Releases statements). Common best practices are summarized on [keepachangelog.com](https://keepachangelog.com).

**Comment by mickaelpois** [comment] 2019-07-18 09:49
Hello @rclement and thanks for this very complete feedback.
I totally agree with you on most of the suggestions / complains.

**Release notes, docs & infos**
We will significantly improve the way we inform all the community ASAP, and be more precise on each feature or breaking changes going live. Breaking changes will be highlighted, and changelog will be better used and updated.
As MANGOPAY is growing fast, we're aware our old release process is not relevant anymore, and your expectations goes higher and higher.

*Version bump issues*
As we were facing some deployment issues between Travis CI ans PyPi for a (very) long time, decision was made to update manually our package. 3.8.0 version was already ready to be released (especially because of urgent UBOs feature), that's the reason why 3.7.0 never goes live. That's clearny not a situation we want to reproduce in the future, and we're very sorry about that too.

Next version of this Python SDK (3.9.0) will be released this summer with some new features: be sure I'll personally do my best to make this release as clear and as smooth as possible.

Thanks again for your constructive feedback 👍 

Mickaël

**Comment by mickaelpois** [comment] 2019-09-24 15:58
@rclement CHANGELOG.md has been added and Travis CI has been fixed.

Our next steps in the following weeks:
- check every opened issues and fix old bugs
- add new features to versions to come
- update CHANGELOG.md with previous updates since 2018 and highlight unreleased versions or unusable ones.

**Closed by mickaelpois** 2019-09-24 15:58 UTC
Labels: enhancement needed, on our roadmap > 1 month
