### ISSUE TITLE
How to silent the SSLVerification issue

### ISSUE THREAD

**Issue by applequist** [Mangopay/mangopay2-python-sdk#40] opened 2016-03-11 18:45 UTC
Hi,

I've cloned the repository and try to run the test suite but I get tons of SSLVerification warning which I tried to fix as mentioned in the README:
I modified `buildNewMangoPayApi` in TestBase(testbase.py) with my client id and password and the following line:
`dk.Config.SSLVerification = certifi.where()`
which point to cacert.pem file of my python distribution:
`/Users/brieuc/repos/mangopay2-python-sdk/venv/lib/python3.5/site-packages/certifi/cacert.pem`

But I still get the warning:
```
...../Users/brieuc/repos/mangopay2-python-sdk/venv/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
./Users/brieuc/repos/mangopay2-python-sdk/venv/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)

```

Any idea what I'm doing wrong ?

**Comment by hobailey** [comment] 2016-03-18 19:23
Hi @applequist, are you still having this problem? We've tested it on Windows and Python v3.4 and weren't able to reproduce the issue. Are you using Windows too, or Linux?

**Comment by applequist** [comment] 2016-03-18 19:29
Well, it's weird when trying to run the test from the clone project I still have the warnings. 
When running my unit tests, I don't have the warning... most of the time... I'm new to python and still have a lot to figure out...
PS: I'm using a Mac.

**Comment by hobailey** [comment] 2016-03-18 19:31
Hmm, strange. Well I'll close this for now since it can't be systematically reproduced, but please do let me know if you make any headway with the issue :-)

**Closed by hobailey** 2016-03-18 19:31 UTC
